name: life_calendar2
description: "Life calendar in weeks"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  logger: ^2.5.0
  freezed_annotation: ^3.0.0
  sqflite: ^2.4.2
  json_annotation: ^4.9.0
  shared_preferences: ^2.5.3
  flutter_bloc: ^9.1.1
  go_router: ^15.1.2
  flutter_launcher_icons: ^0.14.3
  flutter_native_splash: ^2.4.6
  equatable: ^2.0.7
  flutter_localizations:
    sdk: flutter
  intl: any
  uuid: ^4.5.1
  flutter_expandable_fab: ^2.5.2
  image_picker: ^1.2.0
  yandex_mobileads: ^7.16.0
  url_launcher: ^6.3.2
  path_provider: ^2.1.5
  flutter_archive: ^6.0.3
  file_saver: ^0.3.1
  file_picker: ^10.3.3
  custom_refresh_indicator: ^4.0.1
  provider: ^6.1.5+1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  build_runner: ^2.4.15
  freezed: ^3.0.6
  json_serializable: ^6.9.5

flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/onboarding/
    - assets/
